name: CI

on:
    push:
        branches: [ main ]
    pull_request:
        branches: [ main ]
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v5

            - name: Set up Go
              uses: actions/setup-go@v6
              with:
                go-version: '1.27.0'
            
            - name: Run tests
              working-directory: backend
              run: go test ./...
            
            - name: Run vet 
              working-directory: backend
              run: go vet ./...

            - name: Build application
              working-directory: backend
              run: go build -o technical_spec_api .

            # - name: Deploy to Vercel
            #  if: github.event_name == 'push' && github.ref == 'refs/heads/main'
            #  env:
            #    VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
            #  run: npx vercel --prod --yes --scope=sadnorth